### PR TITLE
[KOGITO-1770] Renaming examples in the Kogito WebSite

### PR DESCRIPTION
**Pull request by ricardozanini**
See:
https://issues.redhat.com/browse/KOGITO-1770

### CODE REVIEW

**Comment by sterobin** [comment]
@ricardozanini This is fine with me, but just note that this content is going to be taken down entirely anyway soon once @ibek merges his redesign of the website.

**Review by sterobin — APPROVED** [review]

**Comment by ricardozanini** [comment]
@ibek can you apply your to your PR this renaming?

**Comment by sterobin** [comment]
@ricardozanini , @ibek , this shouldn't impact the redesigned website at all because in Ivo's redesign, it just overviews the product and then links to all our docs. No mention of examples, etc. If any examples are mentioned, that content should likewise be taken down.

**Comment by spolti** [comment]
Is this PR ready to merge?

**Comment by ricardozanini** [comment]
@ibek could you please take a look?

**Review by cristianonicolai — APPROVED** [review]

**Comment by ibek** [comment]
@ricardozanini I completely remove the get started content as you can see in the PR https://github.com/kiegroup/kogito-website/pull/27/files

**Comment by ricardozanini** [comment]
> @ricardozanini I completely remove the get started content as you can see in the PR https://github.com/kiegroup/kogito-website/pull/27/files

I'm closing this one then, thanks! :)

**Pull request closed without merging**
