### PR TITLE
improved quarkus quide to use quarkus maven goals instead of kogito a…

### PR DESCRIPTION
**Pull request by mswiderski**
…rchetype to generate projects

### CODE REVIEW

**Comment by adelasofia** [comment]
@mswiderski This looks good 👍 

One thing to note: if you want to remove the spaces shown on [this screenshot](https://www.dropbox.com/s/bqsgpokel2jtknk/Screenshot%202019-08-01%2008.33.38.png?dl=0), you would need to remove the indentation on the code inside the `<pre>` tags. When you use pre, you should format its content to be exactly as you want it to be rendered. `<pre>` tags are for preformatted text.

If it's not clear I can make the change so you can see it.

**Review by adelasofia — APPROVED** [review]

**Comment by mswiderski** [comment]
@adelasofia updated, could you please let me know if this is what you meant?

**Comment by adelasofia** [comment]
@mswiderski that's exactly it 👍

**Comment by mswiderski** [comment]
Thanks @adelasofia

**Pull request merged**
